import fs from 'fs';
import path from 'path';

/**
 * SkillManager.js
 * 
 * Manages the persistence of learned skills (Code snippets generated by ToolCreatorEngine)
 * It maintains a skills_manifest.json which acts as a library index.
 */
export class SkillManager {
    constructor(agent) {
        this.agent = agent;
        const profilePath = agent.prompts.getProfilePath();

        // Save skills relative to profile data
        this.libraryPath = path.join(profilePath, 'skill_library');
        this.manifestPath = path.join(this.libraryPath, 'skills_manifest.json');

        this.manifest = {
            version: "1.0",
            skills: {}
        };

        this.initLibrary();
    }

    initLibrary() {
        if (!fs.existsSync(this.libraryPath)) {
            fs.mkdirSync(this.libraryPath, { recursive: true });
        }

        if (fs.existsSync(this.manifestPath)) {
            try {
                const data = fs.readFileSync(this.manifestPath, 'utf8');
                this.manifest = JSON.parse(data);
                console.log(`[SkillManager] 📚 Loaded Skill Library. Found ${Object.keys(this.manifest.skills).length} skills.`);
            } catch (err) {
                console.error('[SkillManager] ⚠️ Error loading skill manifest:', err.message);
            }
        } else {
            this.saveManifest();
        }
    }

    saveManifest() {
        try {
            fs.writeFileSync(this.manifestPath, JSON.stringify(this.manifest, null, 4));
        } catch (err) {
            console.error('[SkillManager] ⚠️ Error saving skill manifest:', err.message);
        }
    }

    /**
     * Add a newly created tool to the persistent library
     * @param {string} name 
     * @param {string} description 
     * @param {string} codePath 
     * @param {Array} tags 
     */
    addSkill(name, description, codePath, tags = []) {
        this.manifest.skills[name] = {
            description,
            path: codePath,
            tags,
            dateAdded: new Date().toISOString(),
            usageCount: 0,
            successRate: 1.0
        };
        this.saveManifest();
        console.log(`[SkillManager] 📖 Skill '${name}' added to Persistent Library.`);
    }

    /**
     * Get a specific skill by name
     */
    getSkill(name) {
        return this.manifest.skills[name] || null;
    }

    /**
     * Get all registered dynamic skills
     */
    getAllSkills() {
        return this.manifest.skills;
    }

    /**
     * Update skill metrics (for RAG priority)
     */
    updateSkillMetrics(name, success = true) {
        const skill = this.manifest.skills[name];
        if (skill) {
            skill.usageCount = (skill.usageCount || 0) + 1;
            // Simple moving average for success rate
            const currentRate = skill.successRate || 1.0;
            const targetRate = success ? 1.0 : 0.0;
            skill.successRate = (currentRate * 0.8) + (targetRate * 0.2);
            this.saveManifest();
        }
    }
}
