
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * ToolCreatorEngine: Phase 7 Dynamic Skill Generation
 * 
 * Orchestrates the creation of new MCP-compatible skills/tools
 * using the UnifiedBrain's high-IQ model.
 */
export class ToolCreatorEngine {
    constructor(agent) {
        this.agent = agent;
        // Use KnowledgeStore path if available, fallback to default
        this.dynamicSkillsPath = this.agent.knowledge
            ? this.agent.knowledge.getPath('created_tools')
            : path.join(__dirname, '../../../src/skills/library/dynamic');

        // Ensure directory exists
        if (!fs.existsSync(this.dynamicSkillsPath)) {
            fs.mkdirSync(this.dynamicSkillsPath, { recursive: true });
        }

        console.log('[ToolCreator] Initialized');
    }

    /**
     * Create a new tool for a specific need
     * @param {string} need - Description of what the tool should do
     * @param {string} context - Context about why it's needed (e.g. "Failed to craft X")
     * @returns {Promise<boolean>} Success
     */
    async createTool(need, context = '') {
        console.log(`[ToolCreator] 🛠️ Generating tool for: "${need}"`);

        try {
            // 1. Generate Tool Definition via Brain
            const toolDef = await this.agent.brain.generateTool(need, context);

            if (!toolDef || !toolDef.schema || !toolDef.code) {
                throw new Error('Brain returned invalid tool definition');
            }

            const { schema, code } = toolDef;
            const name = schema.name;

            // 2. Validate Tool Name
            if (!/^[a-z0-9_]+$/.test(name)) {
                throw new Error(`Invalid tool name "${name}". Must be snake_case.`);
            }

            // 3. Construct File Content
            const fileContent = this._buildFileContent(schema, code);

            // 4. Save to Disk
            const filePath = path.join(this.dynamicSkillsPath, `${name}.js`);
            fs.writeFileSync(filePath, fileContent);
            console.log(`[ToolCreator] 💾 Saved tool to ${filePath}`);

            // 5. Register with ToolRegistry (Hot Reload)
            // We need to import the file we just wrote.
            // Since it's an ES module, we might need a cache buster or dynamic import.
            try {
                // Register dynamically
                // Note: File-based registration is better for persistence.
                // We mock the metadata for immediate registration if possible,
                // or just load the file.
                await this.agent.toolRegistry._loadSkill(filePath);

                this.agent.bot.chat(`I've learned a new skill: ${name}!`);

                // Register with KnowledgeStore
                if (this.agent.knowledge) {
                    this.agent.knowledge.registerTool(name, schema.description, {
                        source: 'tool_creator',
                        path: filePath
                    });
                }

                return true;

            } catch (regErr) {
                console.error('[ToolCreator] Registration failed:', regErr);
                // Try to delete broken file
                // fs.unlinkSync(filePath);
                return false;
            }

        } catch (error) {
            console.error('[ToolCreator] Tool generation failed:', error);
            this.agent.bot.chat(`I tried to create a tool for that, but my brain hurt.`);
            return false;
        }
    }

    _buildFileContent(schema, code) {
        // Clean code (remove async if double wrapping occurs)
        let cleanCode = code.trim();
        if (cleanCode.startsWith('async (agent, params) =>')) {
            // format is good
        } else if (cleanCode.startsWith('async function')) {
            // might be named, convert to arrow or anonymous
        }

        // We wrap the code implementation in a default export

        return `
/**
 * ${schema.description}
 * Generated by ToolCreatorEngine
 */

export const metadata = {
    name: '${schema.name}',
    description: '${schema.description}',
    parameters: ${JSON.stringify(schema.parameters, null, 4)},
    tags: ['dynamic', 'generated'],
    usageCount: 0
};

export default ${cleanCode};
`;
    }
}
